<?xml version="1.0"?>

<robot name="rover2" xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:property name="r" value="0.2"/>
    <xacro:property name="h" value="0.2"/>
    <xacro:property name="wheel_mass" value="10"/>
    <xacro:property name="motor_mass" value="3"/>
    <xacro:property name="wheel_support1_length" value="0.3"/>
    <xacro:property name="wheel_support2_length" value="0.2"/>
    <xacro:property name="chassis_length" value="1"/>
    <xacro:property name="pi" value="3.1415926535897931"/>
    <xacro:property name="orientation_part_1" value="${pi/2} 0 ${pi/2}"/>
    <xacro:property name="orientation_part_2" value="0 0 ${pi/2}"/>
    <xacro:property name="wheel_rientation" value="0 0 ${pi/2}"/>
    
    
    <link name="base_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="60"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>

        <visual >
            <origin xyz="0.0 0.0 0.68" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="1 1 0.2"/>
            </geometry>

            <material name="grey">
                <color rgba="0.2 0.2 0.2 1.0"/>
            </material>

        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.68" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="1 1 0.3"/>
            </geometry>
        </collision>
        
    </link>

    <xacro:macro name="wheel_support" params="name2 name1 wheel_name joint_name pos1 pos2 dir motor_joint joint_support_motor" >
        <link name="${name2}">

            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="${orientation_part_2}"/>
                <mass value="${motor_mass}"/>
                <inertia  ixx="0.0" ixy = "0" ixz = "0" iyy="0" iyz = "0" izz="0"/>
            </inertial>

            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${orientation_part_2}"/>
                <geometry>
                    <box size="0.15 ${wheel_support2_length} 0.06"/>
                </geometry>
                <material name="white">
                    <color rgba="1.0 1.0 1.0 1.0"/>
                </material>
            </visual>

            <collision>
                <geometry>
                    <box size="0.15 ${wheel_support2_length} 0.06"/>
                </geometry>
            </collision>

        </link>

        <link name="${name1}">

            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="${orientation_part_1}"/>
                <mass value="${motor_mass}"/>
                <inertia  ixx="0.0" ixy = "0" ixz = "0" iyy="0" iyz = "0" izz="0"/>
            </inertial>

            <visual>
                <origin rpy="${orientation_part_1}"/>
                <geometry>
                    <box size="0.15 ${wheel_support1_length} 0.06"/>
                </geometry>
                <material name="white">
                    <color rgba="1.0 1.0 1.0 1.0"/>
                </material>
            </visual>

            <collision>
                <geometry>
                    <box size="0.15 ${wheel_support1_length} 0.06"/>
                </geometry>
            </collision>
            

        </link>

        

        <!--Wheel connected by a continuous joint-->

        <link name="${wheel_name}">

            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 ${pi/2} ${pi/2}"/>
                <mass value="${wheel_mass}"/>
                <inertia  ixx="${wheel_mass*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${wheel_mass*(3*r*r+h*h)/12}" iyz = "0" izz="${wheel_mass*r*r/2}"/>
            </inertial>

            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 ${pi/2} ${pi/2}"/>
                <geometry>
                    <cylinder radius="${r}" length="${h}"/>
                </geometry>
                <material name="dark_blue">
                    <color rgba="0.0 0.4 0.5 1.0"/>
                </material>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 ${pi/2} ${pi/2}"/>
                <geometry>
                    <cylinder radius="${r}" length="${h}"/>
                </geometry>
            </collision>

        </link>

        <!--JOINT SECTION-->
        
        <joint name="${motor_joint}" type="continuous">
            <parent link="${name1}"/>
            <child link="${wheel_name}"/>
            <axis xyz="0 1 0"/>
            <origin xyz="${-(wheel_support2_length/2)-0.03} 0 ${-(wheel_support1_length/2)}" rpy="${wheel_rientation}"/>
            <limit effort="30.0" velocity="100.0"/>
        </joint>

        <joint name="${joint_name}" type="revolute">
            <origin xyz="${pos1} ${pos2} 0.55" rpy="0.0 0.0 ${dir}"/>
            <parent link="base_link"/>
            <child link="${name2}"/>
            <axis xyz="0 0 1"/>
            <limit lower="-${pi}" upper="${pi}" effort="1.0" velocity="1.0"/>
        </joint>


        <joint name="${joint_support_motor}" type="fixed">
                <parent link="${name2}"/>
                <child link="${name1}"/>
                <origin xyz="${(wheel_support2_length/2)+0.03} 0.0 ${-(wheel_support1_length/2)+0.03}" rpy="0.0 0.0 0.0"/>
        </joint>

        <gazebo reference="${wheel_name}">
            <mu1 value="1.0"/>
            <mu2 value="1.0"/>
            <kp  value="10000000.0" />
            <kd  value="1.0" />
            <fdir1 value="1 0 0"/>
            <material>Gazebo/Blue</material>
        </gazebo>

        <transmission name="${motor_joint}_transmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${motor_joint}">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${wheel_name}_motor">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>10</mechanicalReduction>
            </actuator>
        </transmission>

        <transmission name="${joint_name}_transmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${joint_name}">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${name2}_motor">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

    <xacro:wheel_support name1="support_right_front_1" name2="support_right_front_2" wheel_name="wheel_right_front" joint_name="steering_right_front" pos1="+0.4" pos2="0.4" dir="0" motor_joint="motor_right_front" joint_support_motor="joint1"/>
    <xacro:wheel_support name1="support_left_front_1" name2="support_left_front_2" wheel_name="wheel_left_front"  joint_name="steering_left_front" pos1="-0.4" pos2="0.4" dir="${pi}" motor_joint="motor_left_front" joint_support_motor="joint2"/>
    <xacro:wheel_support name1="support_right_rear_1" name2="support_right_rear_2" wheel_name="wheel_right_rear" joint_name="steering_right_rear" pos1="+0.4" pos2="-0.4" dir="0" motor_joint="motor_right_rear" joint_support_motor="joint3"/>
    <xacro:wheel_support name1="support_left_rear_1" name2="support_left_rear_2" wheel_name="wheel_left_rear"  joint_name="steering_left_rear" pos1="-0.4" pos2="-0.4" dir="${pi}" motor_joint="motor_left_rear" joint_support_motor="joint4"/>

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/rover2</robotNamespace>
            <legacyModeNS>true</legacyModeNS>
        </plugin>
    </gazebo>

</robot>